# Ruby CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-ruby/ for more details
#
version: 2
jobs:
  build:
    docker:
      # specify the version you desire here
       - image: circleci/ruby:2.4.1-node-browsers
      
    working_directory: ~/repo

    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "Gemfile" }}

      - run:
          name: install dependencies
          command: |
            bundle install --jobs=4 --retry=3 --path vendor/bundle

      - save_cache:
          paths:
            - ./vendor/bundle
          key: v1-dependencies-{{ checksum "Gemfile" }}
        
      - run: 
          name: install memcached
          command: |
            sudo apt-get update && sudo apt-get install -y memcached
            sudo service start memcached || true
            memcached -d || true
            echo "checking if memcached is running...."
            ps -ef | grep [m]emcached

      - run:
          name: install sym bash helpers
          command: |
            bundle exec exe/sym -B ~/.bash_profile
            [[ -f ~/.sym.completion.bash ]] || exit 1
            [[ -f ~/.sym.symit.bash ]] || exit 1

      - run:
          name: run tests
          command: |
            bundle exec rspec --version
            bundle exec exe/sym --version
            echo password | bundle exec rspec --backtrace --format documentation

